SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/About.cshtml.cs
using ComponentSpace.Saml2.Utility;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiddlewareIdentityProvider.Pages
{
    public class AboutModel : PageModel
    {
        public AboutModel(ILicense license)
        {
            string licenseType;

            if (license.IsLicensed)
            {
                licenseType = "Licensed";
            }
            else
            {
                licenseType = $"Evaluation (Expires {license.Expires.ToShortDateString()})";
            }

            ProductInformation = $"ComponentSpace.Saml2, Version={license.Version}, {licenseType}";
        }

        public string ProductInformation { get; set; }

        public void OnGet()
        {
        }
    }
}

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiddlewareIdentityProvider.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MiddlewareIdentityProvider.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Index.cshtml.cs
using ComponentSpace.Saml2.Middleware;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;

namespace MiddlewareIdentityProvider.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnGetInitiateSingleSignOn()
        {
            // Pass control to the SAML middleware for IdP-initiated SSO.
            var url = SamlMiddlewareDefaults.InitiateSingleSignOnPath;

            if (!string.IsNullOrEmpty(Request.PathBase))
            {
                var stringBuilder = new StringBuilder();

                stringBuilder.Append(Request.PathBase);
                stringBuilder.Append(url);

                url = stringBuilder.ToString();
            }

            return LocalRedirect(url);
        }
    }
}

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiddlewareIdentityProvider.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>
    This example demonstrates using the ComponentSpace SAML v2.0 library's middleware to enable SAML single sign-on
    as the identity provider.
</p>
<p>
    It includes support for identity provider (IdP) and service provider (SP) initiated
    single sign-on (SSO) and single logout (SLO).
</p>
<h4>Product Information</h4>
<p>
    @Model.ProductInformation
</p>

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<p>If you need assistance, please feel free to contact us by email or on our <a href="https://www.componentspace.com/forums" target="_blank">online forums</a>.</p>

<address>
    <strong>Support:</strong>   <a href="mailto:support@componentspace.com">support@componentspace.com</a><br />
    <strong>Sales:</strong> <a href="mailto:sales@componentspace.com">sales@componentspace.com</a>
</address>

SAML for .NET Core/Examples/SSO/MiddlewareIdentityProvider/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="jumbotron">
    <h1>Middleware Identity Provider</h1>
    <p class="lead">
        This example demonstrates using the ComponentSpace SAML v2.0 library's middleware to enable SAML single sign-on
        as the identity provider.
    </p>
    <p><a asp-page-handler="InitiateSingleSignOn" class="btn btn-primary btn-lg">SSO to the Service Provider</a></p>
</div>